[package]
name = "coopy"
version = "0.1.0"
edition = "2024"

[dependencies]
serde = { version = "1.0.219", features = ["derive"] }
serde_yaml = "0.8.26"
toml = "0.9.5"
clap = { version = "4.5.45", features = ["derive"] }
