# Coopy config settings

[user-settings]
source = "/home/dev/Documents/Rust/test-vaults/source"
target = "/home/dev/Documents/Rust/test-vaults/dest"
folders = ["Blog", "Bases", "Knowledge Base", "Resources", "Self Learning", "Ramblings", "Tech Resources", "Clippings"]
forbidden = ["Personal Stuff", "Politics and History", "Finances", "Self Care", "Tasks"]

